#ifndef TIPOERROR_H_INCLUDED
#define TIPOERROR_H_INCLUDED
#include <iostream>
#include <stdlib.h>

using namespace std;

typedef enum {VENDEDORYAEXISTE, SUPERVISORYAEXISTE, CEDULANOVALIDA, MANZANASNOVALIDA, SUELDONOVALIDO, COMISIONNOVALIDA, FECHANOVALIDA, CANTIDADVENTASNOVALIDA, NOMBRENOVALIDO, SUPERVISORNOEXISTE, VENDEDORNOEXISTE, SUPCARGADO, VENDCARGADO, SETCANTIDADVENTAS} TipoError;

typedef enum {FIJO, ZAFRAL, SUPERVISOR} TipoPersona;

void muestroError (TipoError error);

#endif // TIPOERROR_H_INCLUDED
